import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fcf6ed",
        error: "#b31b25",
        "error-container": "#fb5151",
        "error-dim": "#9f0519",
        "inverse-on-surface": "#a19c95",
        "inverse-primary": "#ff5722",
        "inverse-surface": "#100e09",
        "on-background": "#312e29",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "on-primary": "#ffefeb",
        "on-primary-container": "#470e00",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#581300",
        "on-secondary": "#edf3ff",
        "on-secondary-container": "#004a7e",
        "on-secondary-fixed": "#00365e",
        "on-secondary-fixed-variant": "#00538d",
        "on-surface": "#312e29",
        "on-surface-variant": "#5e5b54",
        "on-tertiary": "#fff2ce",
        "on-tertiary-container": "#594a00",
        "on-tertiary-fixed": "#433700",
        "on-tertiary-fixed-variant": "#645300",
        outline: "#7a766f",
        "outline-variant": "#b1ada5",
        primary: "#ab2d00",
        "primary-container": "#ff7851",
        "primary-dim": "#962700",
        "primary-fixed": "#ff7851",
        "primary-fixed-dim": "#ff5d2b",
        secondary: "#005e9f",
        "secondary-container": "#b3d4ff",
        "secondary-dim": "#00528b",
        "secondary-fixed": "#b3d4ff",
        "secondary-fixed-dim": "#99c7ff",
        surface: "#fcf6ed",
        "surface-bright": "#fcf6ed",
        "surface-container": "#ede7dd",
        "surface-container-high": "#e8e2d7",
        "surface-container-highest": "#e2dcd1",
        "surface-container-low": "#f6f0e6",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dad4c8",
        "surface-tint": "#ab2d00",
        "surface-variant": "#e2dcd1",
        tertiary: "#6d5a00",
        "tertiary-container": "#fdd400",
        "tertiary-dim": "#5f4e00",
        "tertiary-fixed": "#fdd400",
        "tertiary-fixed-dim": "#edc600"
      },
      fontFamily: {
        display: ["var(--font-plus-jakarta-sans)"],
        body: ["var(--font-be-vietnam-pro)"],
        label: ["var(--font-space-grotesk)"],
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0px 20px 40px rgba(49, 46, 41, 0.08)",
        sketch: "2px 2px 0px var(--tw-shadow-color)",
      }
    },
  },
  plugins: [],
};

export default config;
